theme: jekyll-theme-minimal
title: <a href="https://ecastrom.github.io/eocastrom/main">Edgar O. Castro Mendez</a>
logo: "PhotoID.jpg"
description: <p> <a href="mailto:ecastrom@gmu.edu">Email</a> | <a href="https://ecastrom.github.io/eocastrom/cv">CV</a> | <a href="https://ecastrom.github.io/eocastrom/research">Research</a> | <a href="https://ecastrom.github.io/eocastrom/teaching">Teaching</a> <br> 3434 Washington Blvd, Arlington, VA 22201, USA </p>
